import { cn } from "@/utils/helpers";
import { GeistMono as geist_mono } from "geist/font/mono";
import { GeistSans as geist_sans } from "geist/font/sans";
import type { Metadata } from "next";
import "@/styles/tailwind.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={cn("min-h-screen", geist_sans.variable, geist_mono.variable)}
			>
				{children}
			</body>
		</html>
	);
}
